### ISSUE TITLE
Error on /actions/request.html

### ISSUE THREAD

**Issue by payrequestio** [Petertjuh360/da-letsencrypt#40]
When try to generate a new SSL it gives the following error below:
Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in /usr/local/directadmin/plugins/da-letsencrypt/includes/lib/Domain.php on line 109 

Line 109:  throw new \Exception("Error requesting certificate: ". $e->getMessage(), $e->getCode(), $e);

**Comment by Wouter0100** [comment]
Hmm, is it me or seems it to be correct? First param, string, second, code, third, previous exception? Thanks for the issue, I'll look into this.

**Comment by AramVK** [comment]
I found this test at https://3v4l.org/Of6Vv - which would indicate a lower version of PHP. 

Would be helpful to see which version you are running:

`/usr/local/bin/php -v`

**Comment by payrequestio** [comment]
The server runs on PHP 5.6.16

**Comment by henkque** [comment]
I can reproduce this problem when generating a SSL cert for domains with subdomains. When all subdomains are unchecked, this error occurs. When you leave one subdomain on, the cert will be created succesfull.

**Comment by sjerdo** [comment]
If no subdomains are selected, $_POST['subdomains'] will be unset, so considered null. [In this line](https://github.com/Petertjuh360/da-letsencrypt/blob/master/user/actions/request.html#L74) the $_POST['subdomains'] is cast to an array, which will result in null. [In this part of the code](https://github.com/Petertjuh360/da-letsencrypt/blob/master/includes/lib/Domain.php#L99), all subdomains will be included in SAN. See also: [Example of cast to null](https://3v4l.org/9XfAX)

The CSR will be denied by the ACME server, while there were no challenges validated for each subdomain. This will result in an exception.

I don't know why this fatal error occurs tho.

**Comment by zenire** [comment]
I merged the pull request of @sjerdo (thank you by the way!). Could you try again, please?

**Comment by payrequestio** [comment]
@Petertjuh360 it seems fixed now, good job!

**Comment by zenire** [comment]
@hostingwalk Thank you for the feedback. Good to hear it is working now. Thanks to @sjerdo for the fix.

**Comment by barryvdh** [comment]
This doesn't actually fix the problem with the Exception. It just makes sure it's not thrown.

See https://github.com/kelunik/acme/issues/4
The code is not always a float, so when passing it to the next Exception, it fails.

See testcase: https://3v4l.org/ObN47

Solution would be to net use the previous code, but just 0.
